 CREATE   PROCEDURE [dbo].[SaveSOHeaderJson]    
@JsonData NVARCHAR(MAX) = NULL    
AS    
BEGIN    
   
 INSERT INTO POJsonfromERP (     PONUMBER,     JsonData,     createdat ) VALUES (     'Before SO Insert',     @JsonData,     GETDATE() );  
    
    
     

DECLARE @SO TABLE    
(    
    SOERPHeaderId VARCHAR(36),    
    DocId INT,    
    SO_NUMBER VARCHAR(50),    
    SO_DATE DATETIME,    
    SO_REVISION INT,    
    SO_TYPE VARCHAR(50),    
    SO_SubType VARCHAR(50),    
    SO_STATUS VARCHAR(50),    
    HOLD_FLAG BIT,    
    CUSTOMER_ID INT,    
    CUSTOMER_NAME VARCHAR(200),    
    CUSTOMER_NUMBER VARCHAR(50),    
    CUSTOMER_ADDRESS VARCHAR(500),    
    CUSTOMER_GSTIN VARCHAR(20),    
    CUSTOMER_PAN VARCHAR(20),    
    CUSTOMER_CONTACT VARCHAR(100),    
    CUSTOMER_PHONE VARCHAR(20),    
    CUSTOMER_EMAIL VARCHAR(100),    
    CUSTOMER_PO_NUMBER VARCHAR(50),    
    CUSTOMER_COUNTRY NVARCHAR(200),    
    
    SELLER_ORG VARCHAR(200),    
    SELLER_OU_ID INT,    
    SELLER_ADDRESS VARCHAR(500),    
    SELLER_GSTIN VARCHAR(20),    
    SELLER_NAME VARCHAR(200),    
    SELLER_CONTACT VARCHAR(100),    
    SELLER_EMAIL VARCHAR(100),    
    
    SHIP_TO_LOCATION VARCHAR(200),    
    SHIP_TO_ADDRESS VARCHAR(500),    
    SHIP_TO_CONTACT VARCHAR(100),    
    
    BILL_TO_LOCATION VARCHAR(200),    
    BILL_TO_ADDRESS VARCHAR(500),    
    BILL_TO_CONTACT VARCHAR(100),    
    
    PAYMENT_TERMS VARCHAR(50),    
    PAYMENT_TERMS_ID INT,    
    CURRENCY_CODE VARCHAR(10),    
    CONVERSION_RATE DECIMAL(18,6),    
    
    PRICE_LIST_ID INT,    
    PRICE_LIST_NAME VARCHAR(100),    
    
    SUBTOTAL DECIMAL(18,2),    
    TOTAL_TAX_AMOUNT DECIMAL(18,2),    
    GRAND_TOTAL DECIMAL(18,2),    
    
    FREIGHT_TERMS VARCHAR(50),    
    SHIPPING_METHOD VARCHAR(50),    
    INCOTERMS VARCHAR(50),    
    
    SPECIAL_INSTRUCTIONS VARCHAR(MAX),    
    
    ORDER_TYPE_ID BIGINT,    
    ORDER_TYPE_NAME NVARCHAR(200),    
    ORDER_CATEGORY_CODE VARCHAR(30),    
    RETURN_REASON_CODE VARCHAR(30),    
    SOLD_TO_ORG_ID BIGINT,    
    MIXED_ORDER_FLAG BIT,    
    MIXED_TRANSACTION_FLAG BIT,    
    SO_SERVICE_TYPE VARCHAR(100),    
    SO_TRANSACTION_TYPE VARCHAR(100),    
    
    created_by INT,    
    created_at DATETIME,    
    updated_by INT,    
    updated_at DATETIME,    
    deleted_at DATETIME    
)    
    
  
INSERT INTO @SO    
SELECT *    
FROM OPENJSON(@JsonData)    
WITH (    
    SOERPHeaderId VARCHAR(36),    
    DocId INT,    
    SO_NUMBER VARCHAR(50),    
    SO_DATE DATETIME,    
    SO_REVISION INT,    
    SO_TYPE VARCHAR(50),    
    SO_SubType VARCHAR(50),    
    SO_STATUS VARCHAR(50),    
    HOLD_FLAG BIT,    
    
    CUSTOMER_ID INT,    
    CUSTOMER_NAME VARCHAR(200),    
    CUSTOMER_NUMBER VARCHAR(50),    
    CUSTOMER_ADDRESS VARCHAR(500),    
    CUSTOMER_GSTIN VARCHAR(20),    
    CUSTOMER_PAN VARCHAR(20),    
    CUSTOMER_CONTACT VARCHAR(100),    
    CUSTOMER_PHONE VARCHAR(20),    
    CUSTOMER_EMAIL VARCHAR(100),    
    CUSTOMER_PO_NUMBER VARCHAR(50),    
    CUSTOMER_COUNTRY NVARCHAR(200),    
    
    SELLER_ORG VARCHAR(200),    
    SELLER_OU_ID INT,    
    SELLER_ADDRESS VARCHAR(500),    
    SELLER_GSTIN VARCHAR(20),    
    SELLER_NAME VARCHAR(200),    
    SELLER_CONTACT VARCHAR(100),    
    SELLER_EMAIL VARCHAR(100),    
    
    SHIP_TO_LOCATION VARCHAR(200),    
    SHIP_TO_ADDRESS VARCHAR(500),    
    SHIP_TO_CONTACT VARCHAR(100),    
    
    BILL_TO_LOCATION VARCHAR(200),    
    BILL_TO_ADDRESS VARCHAR(500),    
    BILL_TO_CONTACT VARCHAR(100),    
    
    PAYMENT_TERMS VARCHAR(50),    
    PAYMENT_TERMS_ID INT,    
    CURRENCY_CODE VARCHAR(10),    
    CONVERSION_RATE DECIMAL(18,6),    
    
    PRICE_LIST_ID INT,    
    PRICE_LIST_NAME VARCHAR(100),    
    
    SUBTOTAL DECIMAL(18,2),    
    TOTAL_TAX_AMOUNT DECIMAL(18,2),    
    GRAND_TOTAL DECIMAL(18,2),    
    
    FREIGHT_TERMS VARCHAR(50),    
    SHIPPING_METHOD VARCHAR(50),    
    INCOTERMS VARCHAR(50),    
    
    SPECIAL_INSTRUCTIONS VARCHAR(MAX),    
    
    ORDER_TYPE_ID BIGINT,    
    ORDER_TYPE_NAME NVARCHAR(200),    
    ORDER_CATEGORY_CODE VARCHAR(30),    
    RETURN_REASON_CODE VARCHAR(30),    
    SOLD_TO_ORG_ID BIGINT,    
    MIXED_ORDER_FLAG BIT,    
    MIXED_TRANSACTION_FLAG BIT,    
    SO_SERVICE_TYPE VARCHAR(100),    
    SO_TRANSACTION_TYPE VARCHAR(100),    
    
    created_by INT,    
    created_at DATETIME,    
    updated_by INT,    
    updated_at DATETIME,    
    deleted_at DATETIME    
)    
    
-- UPDATE    
UPDATE tgt    
SET     
    tgt.DocId = src.DocId,    
    tgt.SO_NUMBER = src.SO_NUMBER,    
    tgt.SO_DATE = src.SO_DATE,    
    tgt.SO_REVISION = src.SO_REVISION,    
    tgt.SO_TYPE = src.SO_TYPE,    
    tgt.SO_SubType = src.SO_SubType,    
    tgt.SO_STATUS = src.SO_STATUS,    
    tgt.HOLD_FLAG = src.HOLD_FLAG,    
    
    tgt.CUSTOMER_ID = src.CUSTOMER_ID,    
    tgt.CUSTOMER_NAME = src.CUSTOMER_NAME,    
    tgt.CUSTOMER_NUMBER = src.CUSTOMER_NUMBER,    
    tgt.CUSTOMER_ADDRESS = src.CUSTOMER_ADDRESS,    
    tgt.CUSTOMER_GSTIN = src.CUSTOMER_GSTIN,    
    tgt.CUSTOMER_PAN = src.CUSTOMER_PAN,    
    tgt.CUSTOMER_CONTACT = src.CUSTOMER_CONTACT,    
    tgt.CUSTOMER_PHONE = src.CUSTOMER_PHONE,    
    tgt.CUSTOMER_EMAIL = src.CUSTOMER_EMAIL,    
    tgt.CUSTOMER_PO_NUMBER = src.CUSTOMER_PO_NUMBER,    
    tgt.CUSTOMER_COUNTRY = src.CUSTOMER_COUNTRY,    
    
    tgt.SELLER_ORG = src.SELLER_ORG,    
    tgt.SELLER_OU_ID = src.SELLER_OU_ID,    
    tgt.SELLER_ADDRESS = src.SELLER_ADDRESS,    
    tgt.SELLER_GSTIN = src.SELLER_GSTIN,    
    tgt.SELLER_NAME = src.SELLER_NAME,    
    tgt.SELLER_CONTACT = src.SELLER_CONTACT,    
    tgt.SELLER_EMAIL = src.SELLER_EMAIL,    
    
    tgt.SHIP_TO_LOCATION = src.SHIP_TO_LOCATION,    
    tgt.SHIP_TO_ADDRESS = src.SHIP_TO_ADDRESS,    
    tgt.SHIP_TO_CONTACT = src.SHIP_TO_CONTACT,    
    
    tgt.BILL_TO_LOCATION = src.BILL_TO_LOCATION,    
    tgt.BILL_TO_ADDRESS = src.BILL_TO_ADDRESS,    
    tgt.BILL_TO_CONTACT = src.BILL_TO_CONTACT,    
    
    tgt.PAYMENT_TERMS = src.PAYMENT_TERMS,    
    tgt.PAYMENT_TERMS_ID = src.PAYMENT_TERMS_ID,    
    tgt.CURRENCY_CODE = src.CURRENCY_CODE,    
    tgt.CONVERSION_RATE = src.CONVERSION_RATE,    
    
    tgt.PRICE_LIST_ID = src.PRICE_LIST_ID,    
    tgt.PRICE_LIST_NAME = src.PRICE_LIST_NAME,    
    
    tgt.SUBTOTAL = src.SUBTOTAL,    
    tgt.TOTAL_TAX_AMOUNT = src.TOTAL_TAX_AMOUNT,    
    tgt.GRAND_TOTAL = src.GRAND_TOTAL,    
    
    tgt.FREIGHT_TERMS = src.FREIGHT_TERMS,    
    tgt.SHIPPING_METHOD = src.SHIPPING_METHOD,    
    tgt.INCOTERMS = src.INCOTERMS,    
    
    tgt.SPECIAL_INSTRUCTIONS = src.SPECIAL_INSTRUCTIONS,    
    
    tgt.ORDER_TYPE_ID = src.ORDER_TYPE_ID,    
    tgt.ORDER_TYPE_NAME = src.ORDER_TYPE_NAME,    
    tgt.ORDER_CATEGORY_CODE = src.ORDER_CATEGORY_CODE,    
    tgt.RETURN_REASON_CODE = src.RETURN_REASON_CODE,    
    tgt.SOLD_TO_ORG_ID = src.SOLD_TO_ORG_ID,    
    tgt.MIXED_ORDER_FLAG = src.MIXED_ORDER_FLAG,    
    tgt.MIXED_TRANSACTION_FLAG = src.MIXED_TRANSACTION_FLAG,    
    tgt.SO_SERVICE_TYPE = src.SO_SERVICE_TYPE,    
    tgt.SO_TRANSACTION_TYPE = src.SO_TRANSACTION_TYPE,    
    
    tgt.updated_by = src.updated_by,    
    tgt.updated_at = GETDATE()    
FROM SOERPHeader tgt    
JOIN @SO src     
    ON tgt.SOERPHeaderId = src.SOERPHeaderId    
    
-- INSERT    
INSERT INTO SOERPHeader    
(    
    SOERPHeaderId, DocId, SO_NUMBER, SO_DATE, SO_REVISION, SO_TYPE, SO_SubType, SO_STATUS, HOLD_FLAG,    
    CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER, CUSTOMER_ADDRESS, CUSTOMER_GSTIN, CUSTOMER_PAN,    
    CUSTOMER_CONTACT, CUSTOMER_PHONE, CUSTOMER_EMAIL, CUSTOMER_PO_NUMBER, CUSTOMER_COUNTRY,    
    SELLER_ORG, SELLER_OU_ID, SELLER_ADDRESS, SELLER_GSTIN, SELLER_NAME, SELLER_CONTACT, SELLER_EMAIL,    
    SHIP_TO_LOCATION, SHIP_TO_ADDRESS, SHIP_TO_CONTACT,    
    BILL_TO_LOCATION, BILL_TO_ADDRESS, BILL_TO_CONTACT,    
    PAYMENT_TERMS, PAYMENT_TERMS_ID, CURRENCY_CODE, CONVERSION_RATE,    
    PRICE_LIST_ID, PRICE_LIST_NAME,    
    SUBTOTAL, TOTAL_TAX_AMOUNT, GRAND_TOTAL,    
    FREIGHT_TERMS, SHIPPING_METHOD, INCOTERMS,    
    SPECIAL_INSTRUCTIONS,    
    ORDER_TYPE_ID, ORDER_TYPE_NAME, ORDER_CATEGORY_CODE, RETURN_REASON_CODE,    
    SOLD_TO_ORG_ID, MIXED_ORDER_FLAG, MIXED_TRANSACTION_FLAG,    
    SO_SERVICE_TYPE, SO_TRANSACTION_TYPE,    
    created_by, created_at, updated_by, updated_at, deleted_at    
)    
SELECT     
    src.SOERPHeaderId, src.DocId, src.SO_NUMBER, src.SO_DATE, src.SO_REVISION, src.SO_TYPE, src.SO_SubType, src.SO_STATUS, src.HOLD_FLAG,    
    src.CUSTOMER_ID, src.CUSTOMER_NAME, src.CUSTOMER_NUMBER, src.CUSTOMER_ADDRESS, src.CUSTOMER_GSTIN, src.CUSTOMER_PAN,    
    src.CUSTOMER_CONTACT, src.CUSTOMER_PHONE, src.CUSTOMER_EMAIL, src.CUSTOMER_PO_NUMBER, src.CUSTOMER_COUNTRY,    
    src.SELLER_ORG, src.SELLER_OU_ID, src.SELLER_ADDRESS, src.SELLER_GSTIN, src.SELLER_NAME, src.SELLER_CONTACT, src.SELLER_EMAIL,    
    src.SHIP_TO_LOCATION, src.SHIP_TO_ADDRESS, src.SHIP_TO_CONTACT,    
    src.BILL_TO_LOCATION, src.BILL_TO_ADDRESS, src.BILL_TO_CONTACT,    
    src.PAYMENT_TERMS, src.PAYMENT_TERMS_ID, src.CURRENCY_CODE, src.CONVERSION_RATE,    
    src.PRICE_LIST_ID, src.PRICE_LIST_NAME,    
    src.SUBTOTAL, src.TOTAL_TAX_AMOUNT, src.GRAND_TOTAL,    
    src.FREIGHT_TERMS, src.SHIPPING_METHOD, src.INCOTERMS,    
    src.SPECIAL_INSTRUCTIONS,    
    src.ORDER_TYPE_ID, src.ORDER_TYPE_NAME, src.ORDER_CATEGORY_CODE, src.RETURN_REASON_CODE,    
    src.SOLD_TO_ORG_ID, src.MIXED_ORDER_FLAG, src.MIXED_TRANSACTION_FLAG,    
    src.SO_SERVICE_TYPE, src.SO_TRANSACTION_TYPE,    
    src.created_by, ISNULL(src.created_at, GETDATE()), src.updated_by, ISNULL(src.updated_at, GETDATE()), src.deleted_at    
FROM @SO src    
WHERE NOT EXISTS (    
    SELECT 1     
    FROM SOERPHeader tgt    
    WHERE tgt.SOERPHeaderId = src.SOERPHeaderId    
);    
    
INSERT INTO POJsonfromERP    
SELECT SO_NUMBER, @JsonData, GETDATE() FROM @SO;    
    
    
SELECT SO_NUMBER FROM @SO;    
    
END 